/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tmaher' at '6/1/16 7:28 PM' with Gradle 2.9
 *
 * @author tmaher, @date 6/1/16 7:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
